'use client';

import { motion, AnimatePresence } from 'framer-motion';
import { X, Sparkles, Brain } from 'lucide-react';

interface AnalysisResultProps {
    isOpen: boolean;
    onClose: () => void;
    analysis: string;
}

export const AnalysisResult = ({ isOpen, onClose, analysis }: AnalysisResultProps) => {
    return (
        <AnimatePresence>
            {isOpen && (
                <>
                    {/* Overlay */}
                    <motion.div
                        initial={{ opacity: 0 }}
                        animate={{ opacity: 1 }}
                        exit={{ opacity: 0 }}
                        onClick={onClose}
                        className="fixed inset-0 bg-stone-900/40 backdrop-blur-[2px] z-40"
                    />

                    {/* Drawer */}
                    <motion.div
                        initial={{ x: '100%' }}
                        animate={{ x: 0 }}
                        exit={{ x: '100%' }}
                        transition={{ type: 'spring', damping: 30, stiffness: 300 }}
                        className="fixed right-0 top-0 h-full w-full max-w-lg bg-white border-l border-stone-200 shadow-2xl z-50 flex flex-col dark:bg-stone-950 dark:border-stone-800"
                    >
                        {/* Header */}
                        <div className="p-6 border-b border-stone-100 dark:border-stone-900 flex justify-between items-center bg-stone-50/50 dark:bg-stone-900/50 backdrop-blur-md">
                            <div className="flex items-center gap-3">
                                <div className="p-2 bg-amber-100 dark:bg-amber-900/30 rounded-lg">
                                    <Brain className="w-5 h-5 text-amber-600 dark:text-amber-400" />
                                </div>
                                <div>
                                    <h2 className="text-xl font-semibold text-stone-900 dark:text-stone-100">Session Analysis</h2>
                                    <p className="text-xs text-stone-500 dark:text-stone-400 font-medium uppercase tracking-wider">AI Insights</p>
                                </div>
                            </div>
                            <button
                                onClick={onClose}
                                aria-label="Close analysis results"
                                className="p-2 hover:bg-stone-200 dark:hover:bg-stone-800 rounded-full transition-colors text-stone-500 dark:text-stone-400"
                            >
                                <X className="w-6 h-6" />
                            </button>
                        </div>

                        {/* Content */}
                        <div className="flex-1 overflow-y-auto p-8 custom-scrollbar">
                            <div className="prose prose-stone dark:prose-invert max-w-none">
                                {analysis.split('\n').map((para, i) => (
                                    para.trim() ? (
                                        <p key={i} className="text-stone-700 dark:text-stone-300 leading-relaxed text-lg mb-4 animate-in fade-in slide-in-from-bottom-2 duration-700 delay-150 fill-mode-both" style={{ animationDelay: `${i * 100}ms` }}>
                                            {para}
                                        </p>
                                    ) : <div key={i} className="h-4" />
                                ))}
                            </div>

                            <div className="mt-12 p-6 bg-amber-50 rounded-2xl border border-amber-100 dark:bg-amber-950/20 dark:border-amber-900/30">
                                <div className="flex items-start gap-3">
                                    <Sparkles className="w-5 h-5 text-amber-500 mt-1 shrink-0" />
                                    <div>
                                        <h4 className="text-sm font-semibold text-amber-900 dark:text-amber-300">Growth Mindset</h4>
                                        <p className="text-sm text-amber-800/80 dark:text-amber-400/80 mt-1">
                                            These insights are generated by analyzing your writing patterns and flow state. Use them to reflect on your cognitive habits.
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>

                        {/* Footer */}
                        <div className="p-6 border-t border-stone-100 dark:border-stone-900 bg-white/50 dark:bg-stone-950/50 backdrop-blur-md">
                            <button
                                onClick={onClose}
                                className="w-full py-4 bg-stone-900 text-stone-50 rounded-2xl font-semibold hover:bg-stone-800 dark:bg-stone-100 dark:text-stone-900 dark:hover:bg-stone-200 transition-all shadow-xl shadow-stone-900/10 active:scale-95 flex items-center justify-center gap-2"
                            >
                                Continue Writing
                            </button>
                        </div>
                    </motion.div>
                </>
            )}
        </AnimatePresence>
    );
};
